const initial = {
  shiah: { label:'שיח', type:'batch', source:'ERP / נתוני ייצור ומכירות', batches:[{name:'A-2407 · Wedding Cake',stage:'מפעל · יישון',target:'92% מכירה תוך 30 יום',result:'',status:'פתוחה'},{name:'T-1182 · תכלת',stage:'ייצור · עיבוד',target:'אחידות מעל 85%',result:'4',status:'נסגרה'}], products:[], criteria:['איכות כללית','אחידות','עמידה ביעד'], bets:[{subject:'A-2407 · Wedding Cake',kind:'תחזית איכות',pick:'4 מתוך 5',user:'מיה אלון',points:'—',status:'פתוח'}], rewards:[['כובע AtzvaVote','318'],['חולצת קהילה','500'],['תקליט','900']] },
  cannabis: { label:'Cannabis', type:'product', source:'UX2C / seach-api.hinbit.com', batches:[], products:[{name:'הולנדי',category:'תפרחת אינדיקה',active:'פעיל'},{name:'רומא',category:'תפרחת היברידית',active:'פעיל'},{name:'Wedding Cake',category:'תפרחת אינדיקה',active:'פעיל'}], criteria:['חוזק השפעה','אחידות','תמורה למחיר','צורת הפרחים','ריח וטעם'], bets:[{subject:'הולנדי מול רומא',kind:'השוואת מוצרים',pick:'הולנדי · חוזק השפעה',user:'תומר ש.',points:'15 נק׳',status:'פתוח'},{subject:'Wedding Cake',kind:'דירוג מוצר יחיד',pick:'5 מתוך 5',user:'הילה ל.',points:'—',status:'נסגר'}], rewards:[['כובע AtzvaVote','318'],['חולצת קהילה','500'],['תקליט','900']] },
  elections: { label:'בחירות', type:'party', source:'מאגר בחירות / הזנה מנהלית', batches:[{name:'רשימת עתיד',stage:'מפלגה · 18 חברי רשימה',target:'מעבר אחוז החסימה',result:'',status:'פעילה',members:'אורי כהן, נטע לוי, יעל ברק'},{name:'הבית החדש',stage:'מפלגה · 14 חברי רשימה',target:'8 מנדטים',result:'',status:'פעילה',members:'גיל רון, דנה פרץ, אסף שרון'}], products:[],criteria:['התאמה לראשות ממשלה','סיכוי לעבור אחוז חסימה','סיכוי להיות שר'],bets:[{subject:'רשימת עתיד',kind:'הימור מנדטים',pick:'12 מנדטים',user:'עידו מ.',points:'80 נק׳',status:'פתוח'},{subject:'נטע לוי',kind:'בחירת שר/ה',pick:'תמונה לשרה',user:'שירה ב.',points:'30 נק׳',status:'פתוח'}],rewards:[['כובע הקהילה','318'],['חולצת קהילה','500'],['תקליט','900']] }
};
let state; try { state=JSON.parse(localStorage.getItem('atzva-admin-data-v3'))||initial; } catch { state=initial; }
let theme='shiah', view='overview', editing=null;
const $=s=>document.querySelector(s); const save=()=>localStorage.setItem('atzva-admin-data-v3',JSON.stringify(state));
const views={overview:'סקירה',catalog:'כל הנתונים',batches:'ניהול ישויות',products:'קטלוג מוצרים',criteria:'קריטריוני דירוג',bets:'ניחושים והימורים',results:'תוצאות וניקוד',rewards:'פרסים',theme:'הגדרות Theme'};
function rows(items, fields, kind){return items.map((x,i)=>`<tr>${fields.map(f=>`<td>${x[f]||'—'}</td>`).join('')}<td class="actions"><button onclick="editItem('${kind}',${i})">עריכה</button><button class="danger" onclick="removeItem('${kind}',${i})">מחיקה</button></td></tr>`).join('')}
function table(headers,body){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}<th></th></tr></thead><tbody>${body||`<tr><td colspan="99" class="empty">אין נתונים להצגה</td></tr>`}</tbody></table></div>`}
function render(){const d=state[theme]; const page=views[view]; let body='';
 if(view==='overview') { const list=d.type==='product'?d.products:d.batches, noun=d.type==='product'?'מוצרים':d.type==='party'?'מפלגות':'אצוות'; body=`<div class="stats"><div class="stat"><small>${noun} פעילות</small><strong>${list.filter(x=>x.status!=='נסגרה').length}</strong></div><div class="stat"><small>דירוגים החודש</small><strong>1,284</strong></div><div class="stat"><small>ניחושים פתוחים</small><strong>${(d.bets||[]).filter(x=>x.status==='פתוח').length}</strong></div><div class="stat"><small>דיוק ממוצע</small><strong>81%</strong></div></div><section class="box"><div class="box-top"><div><h2>פעילות אחרונה</h2><p>${d.source}</p></div><button class="small-primary" onclick="setView('${d.type==='product'?'products':'batches'}')">ניהול ${noun}</button></div>${table([noun.slice(0,-1),'שלב / סוג','יעד / מזהה','סטטוס'],list.map(x=>`<tr><td>${x.name}</td><td>${x.stage||x.category}</td><td>${x.target||'—'}</td><td><span class="tag ${x.status==='נסגרה'?'closed':''}">${x.status||x.active}</span></td><td></td></tr>`).join(''))}</section>`; }
 if(view==='catalog') body=`<section class="box"><div class="box-top"><div><h2>כל הנתונים</h2><p>כל המוצרים, האצוות והמפלגות בכל ה־Themes.</p></div></div>${table(['Theme','שם','סוג','שלב / קטגוריה','יעד / מזהה','סטטוס'],Object.entries(state).flatMap(([k,t])=>[...t.batches.map(x=>`<tr><td>${t.label}</td><td>${x.name}${x.members?`<br><small>חברי רשימה: ${x.members}</small>`:''}</td><td>${t.type==='party'?'מפלגה':'אצווה'}</td><td>${x.stage}</td><td>${x.target}</td><td>${x.status}</td></tr>`),...t.products.map(x=>`<tr><td>${t.label}</td><td>${x.name}</td><td>מוצר</td><td>${x.category}</td><td>—</td><td>${x.active}</td></tr>`)]).join(''))}</section>`;
 if(view==='batches') body=section('אצוות, תחזיות ותוצאות','הגדרת האצוות, יעד ההצלחה ותוצאת האמת בסיום רבעון','הוספת אצווה',table(['שם האצווה','שלב','יעד הצלחה','תוצאה סופית','סטטוס'],rows(d.batches,['name','stage','target','result','status'],'batches')),'batches');
 if(view==='products') body=section('קטלוג מוצרים','המוצרים הזמינים בדירוג החיצוני ובתחרויות השוק. בהמשך יחובר ל־seach-api.','הוספת מוצר',table(['מוצר','קטגוריה','סטטוס'],rows(d.products,['name','category','active'],'products')),'products');
 if(view==='criteria') body=section('קריטריוני דירוג','הקטגוריות שהמשתמשים משווים ומדרגים בכל מוצר.','הוספת קריטריון',table(['קריטריון'],d.criteria.map((x,i)=>`<tr><td>${x}</td><td class="actions"><button onclick="editItem('criteria',${i})">עריכה</button><button class="danger" onclick="removeItem('criteria',${i})">מחיקה</button></td></tr>`).join('')),'criteria');
 if(view==='bets') body=section('ניחושים והימורים',d.type==='product'?'דירוגי מוצר יחיד והשוואות בין שני מוצרים לפי מאפיינים משותפים.':'כל התחזיות וההימורים של המשתתפים.','הוספת ניחוש',table(['על מה','סוג','בחירה / תחזית','משתתף','הימור','סטטוס'],(d.bets||[]).map((x,i)=>`<tr><td>${x.subject}</td><td>${x.kind}</td><td>${x.pick}</td><td>${x.user}</td><td>${x.points}</td><td><span class="tag">${x.status}</span></td><td class="actions"><button onclick="editItem('bets',${i})">עריכה</button><button class="danger" onclick="removeItem('bets',${i})">מחיקה</button></td></tr>`).join('')),'bets');
 if(view==='results') body=`<section class="box"><h2>תוצאות וניקוד</h2><p>כאשר אצווה נסגרת, הזן את תוצאת האמת. המערכת מחשבת נקודות לפי קרבת התחזית.</p>${table(['אצווה','יעד','תוצאה סופית','פעולה'],d.batches.map((x,i)=>`<tr><td>${x.name}</td><td>${x.target}</td><td>${x.result||'ממתין'}</td><td><button class="small-primary" onclick="editItem('batches',${i})">${x.result?'עדכון תוצאה':'הזנת תוצאה'}</button></td></tr>`).join(''))}</section>`;
 if(view==='rewards') body=section('פרסים ונקודות','ניהול קטלוג הפרסים שאליו המשתתפים יכולים לממש את הנקודות שלהם.','הוספת פרס',table(['פרס','עלות בנקודות'],d.rewards.map((x,i)=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td class="actions"><button onclick="editItem('rewards',${i})">עריכה</button><button class="danger" onclick="removeItem('rewards',${i})">מחיקה</button></td></tr>`).join('')),'rewards');
 if(view==='theme') body=`<div class="settings"><section class="box"><h2>פרטי Theme</h2><label class="field">שם Theme<input id="themeName" value="${d.label}" /></label><button class="small-primary" onclick="renameTheme()">שמירת שם</button></section><section class="box"><h2>ניהול Themes</h2><p>כל Theme מחזיק קטלוג, אצוות, קריטריונים, תוצאות ופרסים משלו.</p><button class="small-primary" onclick="newTheme()">יצירת Theme חדש</button></section></div>`;
 const visibleViews=Object.entries(views).filter(([key])=>!(d.type==='product'&&['batches','results'].includes(key))&&!(d.type!=='product'&&key==='products')); $('#app').innerHTML=`<div class="shell"><aside class="side"><div class="side-brand"><span>✦</span> AtzvaVote <small>ADMIN</small></div><div class="theme-picker"><small>THEME פעיל</small><select onchange="switchTheme(this.value)">${Object.entries(state).map(([k,v])=>`<option value="${k}" ${k===theme?'selected':''}>${v.label}</option>`).join('')}</select></div><nav class="nav">${visibleViews.map(([key,label])=>`<button class="${view===key?'active':''}" onclick="setView('${key}')">${label}</button>`).join('')}</nav><div class="side-bottom"><button onclick="logout()">יציאה מהניהול</button></div></aside><main class="content"><header class="top"><div><p class="crumb">ניהול / ${d.label}</p><h1>${page}</h1></div><div class="admin-user">● מנהל מערכת</div></header>${body}</main></div>`;}
function section(title,description,button,content,kind){return `<section class="box"><div class="box-top"><div><h2>${title}</h2><p>${description}</p></div><button class="small-primary" onclick="addItem('${kind}')">+ ${button}</button></div>${content}</section>`}
function setView(v){view=v;render()} function switchTheme(v){theme=v;render()} function logout(){localStorage.removeItem('atzva-admin-auth');location.reload()}
function removeItem(kind,i){if(confirm('למחוק את הפריט?')){state[theme][kind].splice(i,1);save();render()}}
function fields(kind,item={}){if(kind==='batches')return [['name',state[theme].type==='party'?'שם מפלגה':'שם אצווה',item.name],['stage','שלב / פרטי ישות',item.stage],['target','יעד הצלחה',item.target],['result','תוצאה סופית (1-5)',item.result],['status','סטטוס',item.status],...(state[theme].type==='party'?[['members','חברי רשימה (מופרדים בפסיק)',item.members]]:[])];if(kind==='products')return [['name','שם מוצר',item.name],['category','קטגוריה',item.category],['active','סטטוס',item.active]];if(kind==='criteria')return [['value','שם הקריטריון',item]];if(kind==='bets')return [['subject','על מה',item.subject],['kind','סוג ניחוש / הימור',item.kind],['pick','בחירה או תחזית',item.pick],['user','משתתף',item.user],['points','נקודות הימור',item.points],['status','סטטוס',item.status]];return [['name','שם הפרס',item[0]],['points','עלות בנקודות',item[1]]];}
function modal(kind,index){const arr=state[theme][kind], item=index===null?{}:arr[index], fs=fields(kind,item); editing={kind,index};document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg"><form class="modal" onsubmit="saveItem(event)"><h2>${index===null?'הוספת':'עריכת'} פריט</h2>${fs.map(([n,l,v])=>`<label class="field">${l}<input name="${n}" value="${v||''}" required /></label>`).join('')}<div class="modal-actions"><button class="small-primary">שמירה</button><button class="cancel" type="button" onclick="closeModal()">ביטול</button></div></form></div>`)}
function addItem(k){modal(k,null)} function editItem(k,i){modal(k,i)} function closeModal(){$('.modal-bg')?.remove();editing=null}
function saveItem(e){e.preventDefault();const f=new FormData(e.target), {kind,index}=editing, a=state[theme][kind];let x;if(kind==='criteria')x=f.get('value');else if(kind==='rewards')x=[f.get('name'),f.get('points')];else x=Object.fromEntries(f);if(index===null)a.push(x);else a[index]=x;save();closeModal();render()}
function renameTheme(){state[theme].label=$('#themeName').value.trim()||state[theme].label;save();render()} function newTheme(){const name=prompt('שם ה-Theme החדש:');if(!name)return;const key=`theme_${Date.now()}`;state[key]={label:name,batches:[],products:[],criteria:[],rewards:[]};theme=key;save();render()}
function login(){const user=$('#user').value,password=$('#password').value;if(user==='admin'&&password==='changeme123'){localStorage.setItem('atzva-admin-auth','1');boot()}else $('#loginError').textContent='פרטי ההתחברות אינם נכונים.'}
function boot(){if(!localStorage.getItem('atzva-admin-auth')){$('#app').innerHTML=`<main class="login"><form class="login-card" onsubmit="event.preventDefault();login()"><div class="mark">✦</div><h1>ניהול AtzvaVote</h1><p>מרכז ניהול האצוות, המוצרים, תוצאות הניחושים והפרסים לפי Theme.</p><label class="field">שם משתמש<input id="user" value="admin" autocomplete="username"></label><label class="field">סיסמה<input id="password" type="password" autocomplete="current-password" autofocus></label><button class="primary">כניסה למערכת</button><p id="loginError" class="error"></p><p class="hint">גישה מקומית בלבד</p></form></main>`;return}render()} boot();
